# Generated by Django 3.2.5 on 2021-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phoneimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
